"use client";

import { motion } from "framer-motion";
import { ShoppingBag, ArrowUpRight, Heart, Share2 } from "lucide-react";
import Link from "next/link";
import { useState } from "react";

interface Product {
  id: number;
  name: string;
  description: string;
  price: number;
  storeName: string;
  storeSlug: string;
  themeColor: string;
}

interface DiscoverClientProps {
  products: Product[];
}

export function DiscoverClient({ products }: DiscoverClientProps) {
  const [likedIds, setLikedIds] = useState<number[]>([]);

  const toggleLike = (id: number) => {
    setLikedIds(prev => 
      prev.includes(id) ? prev.filter(i => i !== id) : [...prev, id]
    );
  };

  return (
    <div className="min-h-screen bg-[#09090b] pt-32 pb-20 px-6">
      <div className="max-w-7xl mx-auto space-y-12">
        <div className="text-center space-y-4">
          <motion.h1 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-4xl md:text-6xl font-bold text-white tracking-tight"
          >
            Discover <span className="text-brand-purple">Creators</span>
          </motion.h1>
          <motion.p 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="text-gray-400 text-lg max-w-2xl mx-auto"
          >
            Scroll through the best products generated by the community. 
            One photo, infinite possibilities.
          </motion.p>
        </div>

        {products.length === 0 ? (
          <div className="text-center py-20 border border-dashed border-white/10 rounded-3xl">
            <p className="text-gray-500">No products discovered yet. Be the first to publish!</p>
          </div>
        ) : (
          <div className="columns-1 md:columns-2 lg:columns-3 gap-6 space-y-6">
            {products.map((product, index) => (
              <motion.div
                key={product.id}
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.5, delay: index * 0.05 }}
                className="break-inside-avoid glass-card rounded-3xl overflow-hidden group cursor-pointer relative"
              >
                <Link href={`/${product.storeSlug}`}>
                  <div 
                    className="w-full aspect-[4/5] relative flex items-center justify-center overflow-hidden"
                    style={{ background: `linear-gradient(135deg, ${product.themeColor}30, ${product.themeColor}10)` }}
                  >
                    <div className="text-7xl group-hover:scale-110 transition-transform duration-500">
                      {product.name.charAt(0)}
                    </div>
                    
                    {/* Hover Overlay */}
                    <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                      <div className="flex gap-4">
                        <button 
                          onClick={(e) => {
                            e.preventDefault();
                            toggleLike(product.id);
                          }}
                          className={`p-4 rounded-full transition-all ${likedIds.includes(product.id) ? 'bg-red-500 text-white' : 'bg-white text-black hover:bg-red-500 hover:text-white'}`}
                        >
                          <Heart className={`w-6 h-6 ${likedIds.includes(product.id) ? 'fill-current' : ''}`} />
                        </button>
                        <button className="p-4 bg-white text-black rounded-full hover:bg-brand-purple hover:text-white transition-all">
                          <ShoppingBag className="w-6 h-6" />
                        </button>
                      </div>
                    </div>
                  </div>
                </Link>

                <div className="p-6 space-y-4 bg-white/[0.02]">
                  <div className="flex justify-between items-start">
                    <div>
                      <h3 className="text-xl font-bold text-white group-hover:text-brand-purple transition-colors">
                        {product.name}
                      </h3>
                      <Link 
                        href={`/${product.storeSlug}`}
                        className="text-xs text-gray-500 hover:text-white transition-colors flex items-center gap-1"
                      >
                        by {product.storeName}
                        <ArrowUpRight className="w-3 h-3" />
                      </Link>
                    </div>
                    <span className="text-xl font-bold text-white">${product.price}</span>
                  </div>
                  
                  <p className="text-sm text-gray-400 line-clamp-2">
                    {product.description}
                  </p>

                  <div className="flex gap-2 pt-2">
                    <button className="p-2 bg-white/5 hover:bg-white/10 rounded-lg transition-colors">
                      <Share2 className="w-4 h-4 text-gray-400" />
                    </button>
                    <Link 
                      href={`/${product.storeSlug}`}
                      className="flex-1 py-2 rounded-lg bg-white/5 hover:bg-white/10 text-center text-sm font-bold text-white transition-colors"
                    >
                      Visit Store
                    </Link>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
